services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: security-playbooks
    volumes:
      - .:/opt/playbooks
    env_file:
      - .env
    working_dir: /opt/playbooks
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONPATH: "/opt/playbooks"
    stdin_open: true
    tty: true
    command: bash
    restart: unless-stopped
