services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped