services:
  app:
    build: .
    volumes:
      - .:/opt/playbooks
    env_file:
      - .env
    working_dir: /opt/playbooks
    environment:
      PYTHONUNBUFFERED: "1"
    restart: unless-stopped
