[mypy]
python_version = 3.11
mypy_path = src
ignore_missing_imports = True
warn_return_any = True
warn_unused_configs = True
check_untyped_defs = True
show_error_codes = True
implicit_reexport = True

# ---------------------------
# Per-module overrides
# ---------------------------

[mypy-tests.*]
disallow_untyped_defs = False
